#!/bin/bash

file="/etc/passwd"
IFS=$'\n'
i=0

printf "\t| LOGIN\t\t\t|\tUID\t| PATH\t\n"
if [ -f $file ]
then
	for line in $(cat $file | grep -v '#')
	do
		IFS=:
		for value in $line
		do
			if [ $i -eq 0 ]
			then
				printf "\033[32m$value \033[0m"
			elif [ $i -eq 2 ] || [ $i -eq 5 ]
			then
				printf "$value "
			elif [ $i -gt 6 ]
			then
				break
			fi
			i=$(($i + 1))
		done
		i=0
		printf "\n"
	done
else
	printf -e "the file does not exist"
fi
